version: "3.8"
services:
  web:
    container_name: backend
    build:
      context: ././
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: bash -c 'cd neoquiz_app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/neoquiz_app
    env_file:
      - .env
